var mongoose = require("mongoose");
var Schema = mongoose.Schema;

// TODO enter min and max values.

var Default_Values = new Schema({

  headerBackgroundColor:{type: String},
  headerBackgroundHeight:{type: Number},
  sideNavWidth:{type: Number},
  sideNavBackgroundColor:{type: String},
  headMainText:{type: String},
  headMainFont:{type: String},
  headMainTextSize:{type: Number},
  headMainTextColor:{type: String},
  headMainTextBold:{type: Boolean},
  headMainTextItal:{type: Boolean},
  headMainFont:{type: String},
  secondText:{type: String},
  secondTextFont:{type: String},
  secondTextSize:{type: Number},
  secondTextColor:{type: String},
  secondTextBold:{type: Boolean},
  secondTextItal:{type: Boolean},
  thirdText:{type: String},
  thirdTextFont:{type: String},
  thirdTextSize:{type: Number},
  thirdTextColor:{type: String},
  thirdTextBold:{type: Boolean},
  thirdTextItal:{type: Boolean},
  sideTextOne: {type:String},
  sideTextTwo: {type:String},
  sideTextThree: {type:String},
  sideTextFour: {type:String},
  sideTextFive: {type:String},
  sideTextSix: {type:String},
  sideTextSeven: {type:String},
  sideTextEight: {type:String},
  sideTextNine: {type:String},
  sideTexTen: {type:String},
  someValue: {type: Number},
  sideFont: {type: String},
  sideSize: {type: Number},
  sideFontColor:{type: String},
  aboutHead: {type: String},
  aboutHeadSize: {type: Number},
  aboutHeadColor: {type: String},
  aboutHeadBold: {type: Boolean},
  aboutHeadItal: {type: Boolean},
  aboutHeadFont: {type: String},
  aboutSecondOne: {type: String},
  aboutSecondTwo:{type: String},
  aboutSecondThree:{type:String},
  aboutSecondFour:{type:String},
  aboutSecondFive:{type:String},
  aboutOneText:{type:String},
  aboutTwoText:{type:String},
  aboutThreeText:{type:String},
  aboutFourText:{type:String},
  aboutFiveText:{type:String},
  aboutSecondFont:{type:String},
  aboutSecondBold:{type:Boolean},
  aboutSecondSize:{type: Number},
  aboutSecondColor:{type:String},
  aboutSecondItal:{type:Boolean},
  aboutTextFont:{type:String},
  aboutTextBold:{type:String},
  aboutTextSize:{type: Number},
  aboutTextColor:{type:String},
  aboutTextItal: {type:Boolean}

});

module.exports = mongoose.model("Default_Values", Default_Values);
